services:
  # Single Service Deployment: Backend serves frontend
  - type: web
    name: factoresourcing-app
    env: python
    plan: starter
    rootDir: backend
    buildCommand: |
      # Build frontend first
      cd ../frontend
      npm install
      npm run build
      cd ../backend
      # Install backend dependencies
      pip install -r requirements.txt
      # Copy frontend assets
      cp -r ../frontend/dist/* frontend/
    startCommand: python start_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8000
      # Add your OpenAI API key here if you have one
      # - key: OPENAI_API_KEY
      #   value: your-openai-api-key-here
    autoDeploy: true
